/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type LoginOfficerDto = {
  password: string;
  email: string;
};

export type PatientLoginDto = {
  email: string;
  id: number;
};

export type PatientDto = {
  firstName: string;
  lastName: string;
  email: string;
};

export type CreateConsultationDto = {
  consultationType: string;
  medicalCondition: string;
  notes?: string;
  healthcareProviderId: number;
  /**
   * @format date-time
   */
  date: string;
  patient: PatientDto;
};

export type CreateHealthcareProviderDto = {};

export type UpdateHealthcareProviderDto = {};
