/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type HealthCareProvideResponseDto = {
  id: number;
  name: string;
  department: Record<string, any>;
};

export type HealthFacilityResponse = {
  name: string;
};

export type OfficerResponseDto = {
  id: number;
  name: string;
  healthFacility: HealthFacilityResponse;
};

export type PatientResponseDto = {
  firstName: string;
  lastName: string;
  id: number;
};

export type ConsultationResponseDto = {
  id: number;
  date: string;
  consultationType: string;
  medicalCondition: string;
  notes: string;
  officerId: number;
  patientId: number;
  healthcareProviderId: number;
  createdAt: string;
  updatedAt: string;
  healthcareProvider: HealthCareProvideResponseDto;
  officer: OfficerResponseDto;
  patient: PatientResponseDto;
};

export type GetPatientConsultationResponseDto = {
  consultations: ConsultationResponseDto[];
  count: number;
};

export type LoginOfficerDto = {
  password: string;
  email: string;
};

export type LoginOfficerResponseDto = {
  token: string;
  officer: OfficerResponseDto;
};

export type PatientLoginDto = {
  id: number;
};

export type LoginPatientResponseDto = {
  token: string;
  patient: PatientResponseDto;
};

export type PatientDto = {
  firstName: string;
  lastName: string;
  email: string;
};

export type CreateConsultationDto = {
  consultationType: string;
  medicalCondition: string;
  notes?: string;
  healthcareProviderId: number;
  date?: string;
  patient: PatientDto;
};

export type BookConsultationResponseDto = {
  consultation: ConsultationResponseDto;
  message: string;
};
